import assert from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it } from 'node:test';
import { PMTiles } from 'pmtiles';
import { TorrentSource } from '../src/source.js';
import { FakeEngine } from './fake-engine.js';

const here = path.dirname(fileURLToPath(import.meta.url));

/**
 * A real archive read end to end through the source, with a deliberately tiny
 * piece length so header, directory and tile reads each straddle several
 * pieces. Generated by tippecanoe from a single polygon; see the PMTiles repo.
 */
const fixture = new Uint8Array(
  fs.readFileSync(path.join(here, 'data', 'test_fixture_1.pmtiles')),
);

/**
 * The same archive read straight out of memory. Used as the control, so the
 * assertions compare against what PMTiles genuinely produces rather than
 * hard-coded byte counts.
 * @returns {PMTiles} - An archive backed by the raw bytes.
 */
function reference() {
  return new PMTiles({
    getKey: () => 'reference',
    getBytes: async (offset, length) => ({
      data: fixture.slice(offset, Math.min(offset + length, fixture.byteLength))
        .buffer,
    }),
  });
}

describe('end to end against a real PMTiles archive', () => {
  it('reads the header, metadata and a tile', async () => {
    const engine = new FakeEngine(fixture, { pieceLength: 64 });
    const archive = new PMTiles(new TorrentSource(engine));

    const header = await archive.getHeader();
    assert.strictEqual(header.rootDirectoryOffset, 127);
    assert.strictEqual(header.rootDirectoryLength, 25);
    assert.strictEqual(header.tileDataOffset, 399);
    assert.strictEqual(header.maxZoom, 0);

    const metadata = await archive.getMetadata();
    assert.strictEqual(metadata.name, 'test_fixture_1.pmtiles');

    const tile = await archive.getZxy(0, 0, 0);
    const expected = await reference().getZxy(0, 0, 0);
    assert.ok(tile && expected, 'expected tile 0/0/0 to exist');
    assert.deepStrictEqual(
      new Uint8Array(tile.data),
      new Uint8Array(expected.data),
    );

    assert.strictEqual(await archive.getZxy(1, 0, 0), undefined);
  });

  it('prioritises the directory sections it found in the header', async () => {
    const engine = new FakeEngine(fixture, { pieceLength: 64 });
    const archive = new PMTiles(new TorrentSource(engine));

    await archive.getHeader();

    // The fixture has no leaf directories, so only root and metadata are hinted.
    assert.deepStrictEqual(engine.hints, [
      { offset: 127, length: 25, priority: 'critical' },
      { offset: 152, length: 247, priority: 'high' },
    ]);
  });

  it('works when the archive is packed behind another file in the torrent', async () => {
    const engine = new FakeEngine(fixture, {
      pieceLength: 64,
      fileOffset: 1000,
      trailingBytes: 37,
    });
    const archive = new PMTiles(new TorrentSource(engine));

    const tile = await archive.getZxy(0, 0, 0);
    const expected = await reference().getZxy(0, 0, 0);
    assert.ok(tile && expected);
    assert.deepStrictEqual(
      new Uint8Array(tile.data),
      new Uint8Array(expected.data),
    );
    // No read ever ran past the end of the archive file.
    assert.ok(
      engine.reads.every((r) => r.offset + r.length <= fixture.byteLength),
    );
  });

  it('re-reads from the engine when caching is off, and matches', async () => {
    const cached = new FakeEngine(fixture, { pieceLength: 64 });
    const uncached = new FakeEngine(fixture, { pieceLength: 64 });

    const a = await new PMTiles(new TorrentSource(cached)).getZxy(0, 0, 0);
    const b = await new PMTiles(
      new TorrentSource(uncached, { cacheBytes: 0 }),
    ).getZxy(0, 0, 0);

    assert.ok(a && b);
    assert.deepStrictEqual(new Uint8Array(a.data), new Uint8Array(b.data));
    assert.ok(
      uncached.reads.length > cached.reads.length,
      `expected more engine reads without a cache (${uncached.reads.length} vs ${cached.reads.length})`,
    );
  });
});
